---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/geordie/Ping/hosts.yaml"
        group_file: "/home/geordie/Ping/groups.yaml"
        defaults_file: "/home/geordie/Ping/defaults.yaml"

...